from_createのメソッド名をわかりやすく変更
SeijiNumata/sharecamp pull request #83
Opened 2021-08-06 12:36 UTC by SeijiNumata

2021-08-06 20:56 UTC, komagata requested changes

2021-08-06 20:56 UTC, komagata commented on app/controllers/events_controller.rb
> +  def set_from_event_create
英語としておかしいかも？

2021-08-07 08:05 UTC, SeijiNumata commented on app/controllers/events_controller.rb
> +  def set_from_event_create
確かに英語としておかしいですね。
set_came_from_event_createと修正しました！

2021-08-08 18:51 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂

2021-08-10 11:08 UTC, merged